# **Pandas Basics**

### **Install pandas package**

In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\users\justin\.pyenv\pyenv-win\versions\3.14.2\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\justin\.pyenv\pyenv-win\versions\3.14.2\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\justin\.pyenv\pyenv-win\versions\3.14.2\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.9 MB 20.3 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 31.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 28.8 MB/s  0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.2 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: c:\Users\justin\.pyenv\pyenv-win\versions\3.14.2\python.exe -m pip install --upgrade pip

### **Import pandas**

In [1]:
import pandas as pd

## **DataFrames**
A DataFrame is a two-dimensional labeled data structure with columns of potentially 
different data types, similar to a spreadsheet or SQL table. 
It provides a powerful and flexible way to manipulate and analyze structured data in Python, 
offering functionalities for data analysis.

In [2]:
# .DataFrame() is a constructor function used to create new DataFrame
# Creating an Empty DataFrame
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [6]:
# Create a DataFrame using a list of lists
row_data = [["John", 30], ["Jane", 28], ["Smith", 26]]
df = pd.DataFrame(row_data, columns=["Name", "Age"])
df

    Name  Age
0   John   30
1   Jane   28
2  Smith   26

In [7]:
# Create a DataFrame using a dictionary of lists
data = {
    "Name": ["John", "Jane", "Smith"],
    "Age": [30, 28, 26]
}

df = pd.DataFrame(data)
df

    Name  Age
0   John   30
1   Jane   28
2  Smith   26

In [5]:
# Create a DataFrame using a list of dictionaries
data = [
    {"Name": "John", "Age": 30},
    {"Name": "Jane", "Age": 28},
    {"Name": "Smith", "Age": 26}
]

df = pd.DataFrame(data)
df

    Name  Age
0   John   30
1   Jane   28
2  Smith   26

In [9]:
# You can use type() to check the datatype if it is Series or DataFrame
type(df)

pandas.DataFrame

## **Series**

A pandas Series is a one-dimensional labeled array capable of 
holding data of any type (integer, string, float, etc.). 
It's similar to a one-column table or an array with associated labels, 
providing powerful indexing and manipulation capabilities in Python.

In [10]:
series = pd.Series([1, 2, 3, 4, 5])
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [14]:
# You can use type() to check the datatype if it is Series or DataFrame
type(series)

pandas.Series

### **Pandas Data Types**

Numeric:
- Integer (int64): Represents whole numbers (e.g., 10, -5). 
    This is the default integer type in pandas. (64 bit integer)
- Float (float64): Represents numbers with decimals (e.g., 3.14, -12.5).
- Boolean (bool): Represents logical True or False values.
- Object: This is a versatile but less efficient type that can store various data types 
like strings, lists, or custom objects. 
    Pandas uses this type when it cannot infer a more specific data type.

In [15]:
# Integer (int64)
int_series = pd.Series([1, 2, 3, 4, 5])
int_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
# Float (float64)
float_series = pd.Series([3.14, -3.14, 0.0001, -0.0001])
float_series

0    3.1400
1   -3.1400
2    0.0001
3   -0.0001
dtype: float64

In [17]:
# Boolean (bool): (True = 1 or False = 0)
boolean_series = pd.Series([True, False, True, False])
boolean_series

0     True
1    False
2     True
3    False
dtype: bool

In [20]:
# Objects (Object / Mixed Data Types)
object_series = pd.Series([30, 3.14, True, "John"])
object_series

0      30
1    3.14
2    True
3    John
dtype: object

Specialized Data Types:
- Datetime (datetime64[ns]): Represents dates and times with nanosecond precision. 
    Useful for time-series data analysis.
- Timedelta (timedelta64[ns]): Represents durations between timestamps.
- Categorical: Represents categorical data with predefined categories. 
    Efficient for storing limited sets of categories.
- Sparse: Represents sparse data with many missing values. 
    Stores data efficiently by only keeping non-zero values.

In [36]:
# DateTime (Timestamp / datetime64)
# N: to_datetime - conver string to datetime
datetime_series = pd.Series([
    pd.to_datetime("2024-08-27 07:00:00"),
    pd.to_datetime("2024-08-27 08:30:00"),
    pd.to_datetime("2024-08-27 10:00:00"),
    pd.to_datetime("11-09-2024 05:30:00", format="%d-%m-%Y %H:%M:%S"),
    pd.to_datetime("11-2024-09 06:30:59", format="%d-%Y-%m %H:%M:%S")
])
datetime_series

0   2024-08-27 07:00:00
1   2024-08-27 08:30:00
2   2024-08-27 10:00:00
3   2024-09-11 05:30:00
4   2024-09-11 06:30:59
dtype: datetime64[us]

In [ ]:
# Timedelta
timedelta_series = pd.Series([
    pd.Timedelta(days=8, hours=3, minutes=15),
    pd.Timedelta(days=4, hours=3, minutes=15),
    pd.Timedelta(days=1, hours=3, minutes=15)
])
timedelta_series

0   8 days 03:15:00
1   4 days 03:15:00
2   1 days 03:15:00
dtype: timedelta64[us]

In [39]:
# Categorical
categorical_series = pd.Series(
    pd.Categorical(["Marketing", "Sales", "Operations", "IT", "Finance", "HR"])
)
categorical_series

0     Marketing
1         Sales
2    Operations
3            IT
4       Finance
5            HR
dtype: category
Categories (6, str): ['Finance', 'HR', 'IT', 'Marketing', 'Operations', 'Sales']

In [40]:
# Sparse - missing/null values inside of the series
# N: Can include null/missing values of that datatype
sparse_series = pd.Series(
    pd.arrays.SparseArray([30, 31, 32, pd.NA, 29, 42, pd.NA])
)
sparse_series
# NaN - Not a Number

0     30
1     31
2     32
3    NaN
4     29
5     42
6    NaN
dtype: Sparse[object, nan]

### **Changing Data Types**

In [42]:
# Step 1: Check datatype
int_series.dtype

dtype('int64')

In [49]:
# Step 2: Change the datatype (float)

# astype() "as type": returns a new DataFrame where 
#           data is changed to the specified data type.

# Convert the integer to float
float_series = int_series.astype('float64')
float_series

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [55]:
# Converting a float series to a string
string_series = float_series.astype('str')
string_series

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: str

In [61]:
# Cannot convert directly from string to int if the contents of the string contains decimal point.
# Convert to float first, then convert to int

converted_to_float = string_series.astype('float64')
converted_to_float

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [59]:
converted_to_int = converted_to_float.astype('int64')
converted_to_int

0    1
1    2
2    3
3    4
4    5
dtype: int64

**Example: Sales Data Analysis**

You have a dataset of sales transactions that includes the product name, quantity sold, and sale price. 
You want to analyze the data to find the total revenue per product.

In [62]:
data = {
    'Product Name':['Iced Tea', 'Hot Chocolate' , 'Lemonade', 'Coffee', 'Milkshake', 'Tea', 'Smoothie', 'Soda', 'Protein Shake', 'Matcha Latte'],
    'Type': ['Cold', 'Hot', 'Cold', 'Hot', 'Cold', 'Hot', 'Cold', 'Cold', 'Cold', 'Hot'],
    'Stock': [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
    'Quantity Sold':[6, 9, 13, 11, 8, 6, 14, 10, 8, 10],
    'Manufacturing Cost':[7, 10, 6, 8, 9, 7, 10, 11, 8, 9],
    'Market Price':[13, 20, 11, 15, 19, 14, 17, 18, 20, 12],
    'Rating': [1, 3, 5, 4, 3, 2, 5, 3, 2, 3]
}

sales_df = pd.DataFrame(data)
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating
0,Iced Tea,Cold,15,6,7,13,1
1,Hot Chocolate,Hot,15,9,10,20,3
2,Lemonade,Cold,15,13,6,11,5
3,Coffee,Hot,15,11,8,15,4
4,Milkshake,Cold,15,8,9,19,3
5,Tea,Hot,15,6,7,14,2
6,Smoothie,Cold,15,14,10,17,5
7,Soda,Cold,15,10,11,18,3
8,Protein Shake,Cold,15,8,8,20,2
9,Matcha Latte,Hot,15,10,9,12,3

In [67]:
# Step 2: Get the Product Name column
sales_df['Product Name']

0         Iced Tea
1    Hot Chocolate
2         Lemonade
3           Coffee
4        Milkshake
5              Tea
6         Smoothie
7             Soda
8    Protein Shake
9     Matcha Latte
Name: Product Name, dtype: str

In [68]:
# Step 3: Calculate the Total Revenue
sales_df['Total Revenue'] = sales_df['Quantity Sold'] * sales_df['Market Price']
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue
0,Iced Tea,Cold,15,6,7,13,1,78
1,Hot Chocolate,Hot,15,9,10,20,3,180
2,Lemonade,Cold,15,13,6,11,5,143
3,Coffee,Hot,15,11,8,15,4,165
4,Milkshake,Cold,15,8,9,19,3,152
5,Tea,Hot,15,6,7,14,2,84
6,Smoothie,Cold,15,14,10,17,5,238
7,Soda,Cold,15,10,11,18,3,180
8,Protein Shake,Cold,15,8,8,20,2,160
9,Matcha Latte,Hot,15,10,9,12,3,120

In [71]:
# Gross Profit: difference between total revenue and the cost of goods (Cost per product multiply to the quantity sold).
sales_df['Gross Profit'] = sales_df['Total Revenue'] - (sales_df['Quantity Sold'] * sales_df['Manufacturing Cost'])
sales_df

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
0,Iced Tea,Cold,15,6,7,13,1,78,36
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
2,Lemonade,Cold,15,13,6,11,5,143,65
3,Coffee,Hot,15,11,8,15,4,165,77
4,Milkshake,Cold,15,8,9,19,3,152,80
5,Tea,Hot,15,6,7,14,2,84,42
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96
9,Matcha Latte,Hot,15,10,9,12,3,120,30

### **Data Selection**

Pandas provides numerous methods for selecting and indexing data in Series and DataFrames, 
including label-based indexing with .loc, integer-position based indexing with .iloc, and conditional selection.

,Product Name,Type,Stock,Quantity Sold,Manufacturing Cost,Market Price,Rating,Total Revenue,Gross Profit
0,Iced Tea,Cold,15,6,7,13,1,78,36
1,Hot Chocolate,Hot,15,9,10,20,3,180,90
2,Lemonade,Cold,15,13,6,11,5,143,65
3,Coffee,Hot,15,11,8,15,4,165,77
4,Milkshake,Cold,15,8,9,19,3,152,80
5,Tea,Hot,15,6,7,14,2,84,42
6,Smoothie,Cold,15,14,10,17,5,238,98
7,Soda,Cold,15,10,11,18,3,180,70
8,Protein Shake,Cold,15,8,8,20,2,160,96
9,Matcha Latte,Hot,15,10,9,12,3,120,30

### **Data Selection in Series**

### **Data Selection in DataFrame**

#### **Index Location (.iloc)**
- Will get rows based on a number/index.
- Will output into a DataFrame instead of a Series.
> Syntax: [starting_index:ending_index(excluded):step]

#### **Location (.loc)**
- Access a group of rows and columns by label(s) or a boolean array.
> Syntax: [starting_index:ending_index(included):step]

## **Conditional Filtering**

## **Apply**

The apply function in pandas is a powerful tool for working with DataFrames. 
It allows you to apply a custom function to each element (row or column) of the DataFrame 
and return a new DataFrame or Series based on the results.

## Pandas Operators
Data Analysis:

- sum(): Calculates the sum of a Series or DataFrame
- mean(): Calculates the mean of a Series or DataFrame
- median(): Calculates the median of a Series or DataFrame
- std(): Calculates the standard deviation of a Series or DataFrame
- var(): Calculates the variance of a Series or DataFrame

Data Loading and Exploration:

- head(): Shows the first few rows of a DataFrame
- tail(): Shows the last few rows of a DataFrame
- info(): Displays information about the DataFrame, including data types and memory usage
- describe(): Generates summary statistics for each column (mean, standard deviation, etc.)

### **Aggregating Data** (.groupby)

Aggregating data involves summarizing data points into meaningful statistics, 
such as averages, sums, or counts, which can be achieved using GroupBy operations or pivot tables. 
This helps in understanding the dataset at a higher level.